import { SubjectStream, PlanType } from './types.ts';

export const SUBJECTS_BY_STREAM: Record<SubjectStream, string[]> = {
  [SubjectStream.PHYSICAL_SCIENCE]: ['Combined Mathematics', 'Physics', 'Chemistry'],
  [SubjectStream.BIOLOGICAL_SCIENCE]: ['Biology', 'Chemistry', 'Physics', 'Agricultural Science'],
  [SubjectStream.COMMERCE]: ['Accounting', 'Business Studies', 'Economics'],
  [SubjectStream.ARTS]: ['Sinhala', 'History', 'Logic', 'Political Science', 'Economics', 'Buddhist Civilization'],
  [SubjectStream.ENGINEERING_TECH]: ['Engineering Technology', 'Science for Technology', 'ICT'],
  [SubjectStream.BIO_SYSTEMS_TECH]: ['Bio-Systems Technology', 'Science for Technology', 'Agricultural Science']
};

export const PRICING_PLANS = [
  {
    type: PlanType.FREE,
    name: 'Free',
    price: 'Rs. 0',
    duration: 'Forever',
    features: ['20 Questions per Month', 'All Subject Streams', 'Basic Performance Tracking', 'Community Support'],
    buttonText: 'Start for Free'
  },
  {
    type: PlanType.PRO,
    name: 'Pro',
    price: 'Rs. 500',
    duration: 'per month',
    features: ['10 Full MCQ Papers (500 Questions)', 'AI-Powered Explanations', 'Detailed Analytics', 'Past Paper Questions'],
    buttonText: 'Get Pro'
  },
  {
    type: PlanType.PLUS,
    name: 'Plus',
    price: 'Rs. 6,000',
    duration: 'per year',
    features: ['Unlimited Questions', 'Unlimited Full Papers', 'Priority AI Support', 'Expert Tips & Guides', 'Offline Access'],
    buttonText: 'Go Plus'
  }
];

export const SRI_LANKAN_SCHOOLS = [
  "-- Colombo District --",
  "Royal College, Colombo",
  "Ananda College, Colombo",
  "Nalanda College, Colombo",
  "Visakha Vidyalaya, Colombo",
  "Devi Balika Vidyalaya, Colombo",
  "Sirimavo Bandaranaike Vidyalaya, Colombo",
  "Ladies' College, Colombo",
  "Musaeus College, Colombo",
  "St. Bridget's Convent, Colombo",
  "Bishop's College, Colombo",
  "Methodist College, Colombo",
  "St. Paul's Girls' School, Milagiriya",
  "Holy Family Convent, Bambalapitiya",
  "St. Peter's College, Colombo",
  "St. Joseph's College, Colombo",
  "St. Benedict's College, Colombo",
  "Wesley College, Colombo",
  "D.S. Senanayake College, Colombo",
  "Isipathana College, Colombo",
  "Thurstan College, Colombo",
  "Mahanama College, Colombo",
  "Prince of Wales College, Moratuwa",
  "Princess of Wales College, Moratuwa",
  "Lumbini College, Colombo",
  "Asoka Vidyalaya, Colombo",
  "Gothami Balika Vidyalaya, Colombo",
  "Sanghamitta Balika Vidyalaya, Colombo",
  "C.W.W. Kannangara Vidyalaya, Colombo",
  "Ananda Sastralaya, Kotte",
  "Ananda Balika Vidyalaya, Kotte",
  "St. John's College, Panadura",
  "Presbyterian Girls' School, Dehiwala",
  "Hameed Al Husseinie College, Colombo",
  "St. Thomas' College, Mount Lavinia",
  "S. Thomas' Preparatory School, Kollupitiya",
  "Hindu College, Colombo",
  "Ramanathan Hindu Ladies' College, Colombo",
  "Zahira College, Colombo",
  "Carey College, Colombo",
  "St. Sebastian's College, Moratuwa",
  "Our Lady of Victories Convent, Moratuwa",
  "De Mazenod College, Kandana",
  "Holy Cross College, Kalutara",
  "Kalutara Vidyalaya, Kalutara",
  "Tissa Central College, Kalutara",
  "Sri Sumangala College, Panadura",
  "Sri Sumangala Balika Vidyalaya, Panadura",
  "Taxila Central College, Horana",

  "-- Gampaha District --",
  "Bandaranaike College, Gampaha",
  "Rathnavali Balika Vidyalaya, Gampaha",
  "Holy Cross College, Gampaha",
  "Yasodara Devi Balika Vidyalaya, Gampaha",
  "Sri Bodhi College, Gampaha",
  "Maris Stella College, Negombo",
  "Ave Maria Convent, Negombo",
  "Newstead Girls' College, Negombo",
  "St. Mary's College, Negombo",
  "Loyola College, Negombo",
  "Harischandra College, Negombo",
  "Veyangoda Central College",
  "Gurukula College, Kelaniya",
  "Sri Dharmaloka College, Kelaniya",
  "St. Anthony's College, Wattala",
  "St. Anne's Balika Vidyalaya, Wattala",
  "Sapugaskanda Vishaka Balika Vidyalaya",

  "-- Kandy & Central Region --",
  "Trinity College, Kandy",
  "Kingswood College, Kandy",
  "Dharmaraja College, Kandy",
  "St. Anthony's College, Kandy",
  "Vidyartha College, Kandy",
  "Sri Sumangala College, Kandy",
  "St. Sylvester's College, Kandy",
  "Girls' High School, Kandy",
  "Mahamaya Girls' College, Kandy",
  "Pushpadana Girls' College, Kandy",
  "Hillwood College, Kandy",
  "Good Shepherd Convent, Kandy",
  "St. Anthony's Girls' College, Kandy",
  "Viharamahadevi Girls' College, Kandy",
  "Gateway College, Kandy",
  "St. Thomas' College, Matale",
  "Government Science College, Matale",
  "Sanghamitta Balika National School, Matale",
  "Sri Sangamitta Girls' National School, Matale",
  "Christ Church College, Matale",
  "Zahira College, Gampola",
  "Wickramabahu Central College, Gampola",
  "St. Andrew's Girls' College, Nawalapitiya",
  "Gamini National School, Nuwara Eliya",
  "St. Xavier's College, Nuwara Eliya",
  "Good Shepherd Convent, Nuwara Eliya",

  "-- Galle & Southern Region --",
  "Richmond College, Galle",
  "Mahinda College, Galle",
  "St. Aloysius' College, Galle",
  "Vidyaloka College, Galle",
  "Southlands College, Galle",
  "Sanghamitta Balika Vidyalaya, Galle",
  "Rippon Girls' Collective, Galle",
  "Sacred Heart Convent, Galle",
  "Galle Convent, Galle",
  "Dharmasoka College, Ambalangoda",
  "Devananda College, Ambalangoda",
  "Rahula College, Matara",
  "St. Servatius' College, Matara",
  "St. Thomas' College, Matara",
  "Matara Central College",
  "Sujatha Vidyalaya, Matara",
  "Matara Mahamaya College",
  "St. Mary's Convent, Matara",
  "Tangalle Royal College",
  "Tangalle Balika Vidyalaya",
  "Theraputta National School, Ambalantota",
  "Vijaba National School, Hungama",
  "Hambantota Central College",

  "-- Kurunegala & North Western --",
  "Maliyadeva College, Kurunegala",
  "Maliyadeva Balika Vidyalaya, Kurunegala",
  "St. Anne's College, Kurunegala",
  "Holy Family Convent, Kurunegala",
  "Sir John Kotalawala College, Kurunegala",
  "Wayamba Royal College, Kurunegala",
  "Ibbagamuwa Central College",
  "Kuliyapitiya Central College",
  "Saranath College, Kuliyapitiya",
  "St. Mary's College, Chilaw",
  "Carmel Girls' Central College, Chilaw",
  "Joseph Vaz College, Wennappuwa",
  "Holy Family Convent, Wennappuwa",
  "Dhammananda Central College, Puttalam",
  "St. Andrew's Central College, Puttalam",

  "-- Jaffna & Northern Region --",
  "Jaffna Hindu College",
  "Jaffna Central College",
  "St. John's College, Jaffna",
  "St. Patrick's College, Jaffna",
  "Vembadi Girls' High School, Jaffna",
  "Chundikuli Girls' College, Jaffna",
  "Holy Family Convent, Jaffna",
  "Kokuvil Hindu College",
  "Skandavarodaya College, Chunnakam",
  "Hartley College, Point Pedro",
  "Methodist Girls' High School, Point Pedro",
  "Kilinochchi Central College",
  "Mannar Sithy Vinayagar Hindu College",
  "St. Xavier's College, Mannar",
  "Vavuniya Tamil Central College",
  "Mullaitivu Vidyananda College",

  "-- Batticaloa & Eastern Region --",
  "St. Michael's College, Batticaloa",
  "Vincent Girls' High School, Batticaloa",
  "Batticaloa Hindu College",
  "Methodist Central College, Batticaloa",
  "Kattankudy Central College",
  "Trincomalee Sri Koneswara Hindu College",
  "St. Joseph's College, Trincomalee",
  "St. Mary's College, Trincomalee",
  "Trincomalee Girls' High School",
  "Ampara Royal College",
  "Saddhatissa Maha Vidyalaya, Ampara",
  "Dehiattakandiya Central College",

  "-- Anuradhapura & North Central --",
  "Anuradhapura Central College",
  "St. Joseph's College, Anuradhapura",
  "Swarnapali Balika National School, Anuradhapura",
  "Walisinghe Harischandra Maha Vidyalaya, Anuradhapura",
  "Kekirawa Central College",
  "Polonnaruwa Royal College",
  "Polonnaruwa Muslim Central College",
  "Minneriya National School",

  "-- Badulla & Uva Region --",
  "Badulla Central College",
  "Dharmaduta College, Badulla",
  "Uva College, Badulla",
  "Visakha Girls' High School, Badulla",
  "Viharamahadevi Girls' School, Badulla",
  "Bandarawela Central College",
  "St. Joseph's College, Bandarawela",
  "Dharmapala College, Bandarawela",
  "Welimada Central College",
  "Moneragala Royal College",
  "Dutugemunu National School, Buttala",

  "-- Ratnapura & Sabaragamuwa --",
  "Sivali Central College, Ratnapura",
  "Ferguson High School, Ratnapura",
  "St. Aloysius' College, Ratnapura",
  "Ratnapura Buddhist College",
  "Eheliyagoda Central College",
  "Kegalu Vidyalaya, Kegalle",
  "St. Mary's College, Kegalle",
  "St. Joseph's Balika Vidyalaya, Kegalle",
  "Kegalu Balika Vidyalaya, Kegalle",
  "Dudley Senanayake Central College, Tholangamuwa",
  "Ananda Sastralaya, Matugama",
  "St. Mary's College, Matugama",

  "-- Other --",
  "International School Student",
  "Private Candidate",
  "Other School Not Listed"
];